### ISSUE TITLE
"Specified folder/zip file does not contain a valid library" when install 

### ISSUE THREAD

**Issue by huang8812345** [MelodyToys/NeoJS#18]

**Comment by sfranzyshen** [comment]
Can you be more specific ... it's not clear to me what your problem is.

**Comment by sfranzyshen** [comment]
I can only assume that you were trying to import the zip file into the Arduino IDE as a Library. This is not a Library ... but rather a sketch (ino) Extract the archive into your Arduino home folder or somewhere within your local filesystem. Then open the NeoJS.ino file within the Arduino IDE. 

https://github.com/MelodyToys/NeoJS/blob/master/GetStarted.md

I am closing this ... feel free to reopen if this isn't the problem you are having.
